name: Test
on:
  push:
    branches:
      - tullo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # - name: Login to Okteto
    #   uses: tullo/actions/login@tullo
    #   id: login
    #   with:
    #     token: ${{ secrets.OKTETO_TOKEN }}

    - name: Get Kubeconfig
      uses: tullo/actions/namespace@tullo
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: ${{ secrets.OKTETO_NS }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Build
      uses: okteto/actions/build@v3
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }}
        PACKAGE_NAME: action-test
        VCS_REF: ${{ github.sha }}
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: registry.cloud.okteto.net/${{ secrets.OKTETO_NS }}/action-test:${{ github.sha }}
        buildargs: PACKAGE_NAME,VCS_REF,BUILD_DATE

    - uses: tullo/actions/deploy@tullo
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      with:
        namespace: ${{ secrets.OKTETO_NS }}
        manifest: k8s.yml
        tag: tullo/action-test:${{ github.sha }}
        registry: registry.cloud.okteto.net
        waitOn: deployment/action-test
